### ISSUE TITLE
Gedcomx.CLI RecordSetToCSV doesn't extract Person's persistent identifier

### ISSUE THREAD

**Issue by jimmyz** [FamilySearch/gedcomx-csharp#17]
Each person record contains a persistent identifier. It looks like this:

``` xml
<person principal="true" extracted="true" id="p_1">
      <identifier type="http://gedcomx.org/Persistent">https://familysearch.org/pal:/MM9.1.1/MZYH-SSM</identifier>
```

The persistent identifier for the person isn't being extracted as a field in the CSV. This is critical because the person persistent identifier is the key for future updates to the personas.

**Comment by wooddani** [comment]
Duplicate of #18
