### ISSUE TITLE
Gedcomx.CLI RecordSetToCSV doesn't extract Record's persistent identifier

### ISSUE THREAD

**Issue by jimmyz** [FamilySearch/gedcomx-csharp#18]
The Gedcomx.CLI RecordSetToCSV utility will take a GEDCOM X xml record and flatten it into a CSV file with each row containing information about each record. A critical piece of data is missing from the GEDCOM X -> CSV conversion—the persistent identifier. The persistent identifier is located inside of a `<sourceDescription>` element and is the value for the `about` attribute. This persistent identifier needs to be extracted and written to the CSV.

Example of the `sourceDescription` element:

``` xml
<record description="#s1" id="r_187094460">
  <!-- record data... -->
    <sourceDescription about="https://familysearch.org/pal:/MM9.1.2/M421-DGM" resourceType="http://gedcomx.org/Record" id="s1">
      <identifier type="http://gedcomx.org/Persistent">https://familysearch.org/pal:/MM9.1.2/M421-DGM</identifier>
    </sourceDescription>
</record>
```

Note, there may be several `sourceDescription` elements found within a record. The persistent identifier is found within the element that contains the resrource `resourceType` of "http://gedcomx.org/Record".

**Comment by drcjones** [comment]
@jimmyz Could you be more clear on what the bug is here? Is it just changing the identifier type from `Persistent` to `Record` when extracting a record? Is there also something about the "About" attribute's value being incorrect as well?

Also, could you fix the title to match the bug?

Thanks in advance :)

**Comment by jimmyz** [comment]
I believe the title is an accurate description of the issue, but the description doesn't provide enough detail. I'll update the description to provide more background.

**Comment by jimmyz** [comment]
@drcjones The description has been updated. Let me know if that provides better clarity on the issue.

**Comment by wooddani** [comment]
Looking at the output of the test file recordset-1307888.xml to a csv, it contains **only** content from the <text>X</text> tags within the xml. Are you implying that content within the <sourceDescription> that does not contain a text element be put in the csv file?

Another view ...
Using your example about, are you wanting to put "https://familysearch.org/pal:/MM9.1.2/M421-DGM" in the csv file?   

Or are you implying that you want to put contents from this in the csv?
             <coverage>
                <recordType>http://gedcomx.org/Death</recordType>
                <spatial>
                    <original>Gadsden, Etowah, Alabama</original>
                </spatial>
                <temporal>
                    <original>07 Mar 1912</original>
                </temporal>
            </coverage>

Your quick reply is appreciated.

**Comment by jimmyz** [comment]
I'm wanting to put https://familysearch.org/pal:/MM9.1.2/M421-DGM in the CSV. That URI represents the persistent identifier of a GEDCOM X record. Each row of the CSV should contain the persistent identifier.

**Comment by wooddani** [comment]
I'm conversing with others to see about implementation, however regardless of their input, what header should the column be named and do you have a preference on the order of columns? I'm getting into this rather quickly and have yet to find a spec on the csv file.

**Comment by wooddani** [comment]
It appears we plan to add "Identifier" to the end. Will that work for you?

**Comment by wooddani** [comment]
I have the latest on my fork at https://github.com/wooddani/gedcomx-csharp . It is under review. I have only included the persistent identifiers of the record type.

**Comment by jimmyz** [comment]
Perhaps it should be Record_Identifier, since a Person within the record can also have a persistent identifier.

**Comment by wooddani** [comment]
I agree and the change has been updated in my forked repo: https://github.com/wooddani/gedcomx-csharp

**Comment by misbach** [comment]
@wooddani has pushed this fix into the current repo. https://github.com/FamilySearch/gedcomx-csharp/commit/586ebfe93083afa6b8fdedb0954c61497bcaaf5e
