### ISSUE TITLE
Please add some samples and diagrams

### ISSUE THREAD

**Issue by weitzhandler** [FamilySearch/gedcomx-csharp#23]
Hi,

Please add some screenshots of the class-diagram of the Gedcom.Model library.
Also, please include some sample input and output .gedcomx and .xml files containing some sample data to be able to start working with.

Here's one I made myself.
Please refer to it on the main page / screenshots / gedcomx.org website etc.
Or (preferably) make up your own.

http://i.imgur.com/9fGJ65n.png

**Comment by weitzhandler** [comment]
Here's one I made myself.
Please refer to it on the main page / screenshots / gedcomx.org website etc.
Or (preferably) make up your own.

**Comment by wooddani** [comment]
When you are asking for sample input and output data, what are you expecting? The current README.md  (https://github.com/FamilySearch/gedcomx-csharp) has links to several samples. You can also create a sandbox account at https://familysearch.org/developers . This also provides some examples on how to use the API
