### ISSUE TITLE
Documentation is not included with NuGet release

### ISSUE THREAD

**Issue by weitzhandler** [FamilySearch/gedcomx-csharp#24]
Hi,
I added the Gedcomx.Model project via Nuget, and it looks like the documentation is omitted from the released compilation.

Check it out:
![capture](https://cloud.githubusercontent.com/assets/2716316/5641010/2a2e776c-9638-11e4-9855-1e1f47072c30.PNG)

Please fix this

**Comment by wooddani** [comment]
Refer to issue #32. I have build the latest NuGet Package to include documentation.
