### ISSUE TITLE
Interfaces should start with an I by convention

### ISSUE THREAD

**Issue by weitzhandler** [FamilySearch/gedcomx-csharp#25]
Hi,

As per .NET's naming conventions, interface names should alway start with an additional `I`.
Please check [this](http://msdn.microsoft.com/en-us/library/ms229040.aspx) for more info.

The Gedcom X library interfaces do not obey to this convention.
Here are some:
 - [`GedcomxEntryDeserializer`](https://github.com/FamilySearch/gedcomx-csharp/blob/master/GEDCOM%20X%20File/GedcomxEntryDeserializer.cs)
 - [`GedcomxEntrySerializer`](https://github.com/FamilySearch/gedcomx-csharp/blob/master/GEDCOM%20X%20File/GedcomxEntryserializer.cs)
 - [`SupportsLinks`](https://github.com/FamilySearch/gedcomx-csharp/blob/master/Gedcomx.Model/SupportsLinks.cs)
 - [`GedcomModelVisitor`](https://github.com/FamilySearch/gedcomx-csharp/blob/master/Gedcomx.Model/Rt/GedcomxModelVisitor.cs)
 - [`Attributable`](https://github.com/FamilySearch/gedcomx-csharp/blob/master/Gedcomx.Model/Attributable.cs)

Although this is obviously a breaking change, I believe this has no effect, I think we can assume nobody have directly implemented these interfaces.

**Comment by BrannonKing** [comment]
+1. Do it right.

**Comment by stoicflame** [comment]
See #26.
