### ISSUE TITLE
Nuget package is incomplete?

### ISSUE THREAD

**Issue by JamieHirstTwile** [FamilySearch/gedcomx-csharp#32]
Hi

If I start a new project and install the nuget package **FamilySearch.API.SDK** (1.0.5422.31549) - on the first line of SDK code, getting the family tree collection:

`FamilySearchFamilyTree ft = new FamilySearchFamilyTree(useSandbox);`

I get a runtime error stating that the file or assembly **Gedcomx.File** cannot be loaded.

If I then install the nuget package **Gedcomx.File** (1.0.5422.31544) - the same line instead gives a runtime error that it can't find the file or assembly **Link**:

> Could not load file or assembly 'Link, Version=1.0.5416.32154, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

**Comment by shanewalters** [comment]
We had to customize Tavis.Link (see https://github.com/tavis-software/Tavis.Link/pull/5) to correctly parse extension attributes in links. The "Link" class requested comes from https://github.com/FamilySearch/gedcomx-csharp/tree/master/Link.

The Tavis.Link PR was accepted and merged, and most likely released as part of the 2.1 version on NuGet. I think we should drop https://github.com/FamilySearch/gedcomx-csharp/tree/master/Link, and replace it with Tavis.Link from NuGet.

Can you put together a PR with these changes? @stoicflame - should anyone else weigh in?

**Comment by stoicflame** [comment]
> I think we should drop https://github.com/FamilySearch/gedcomx-csharp/tree/master/Link, and replace it with Tavis.Link from NuGet.

:+1: 

> should anyone else weigh in?

No, I don't think so. I think we can go ahead with that change when it's ready.

**Comment by wooddani** [comment]
I have added Tavis.Link, removed Link and updated several other references and provided a review-able fork at https://github.com/wooddani/gedcomx-csharp . At the moment i'm hosting a private NuGet Package store at http://dannugetpackages.azurewebsites.net/ and waiting for a formal review with FamilySearch before a NuGet publish can be done.

This code should now work, however please let me know if you see any issues.
FamilySearchFamilyTree ft = new FamilySearchFamilyTree(useSandbox);
