### ISSUE TITLE
ReadAncestry and ReadDescendancy results don't include d.o.b.

### ISSUE THREAD

**Issue by JamieHirstTwile** [FamilySearch/gedcomx-csharp#33]
Hi,

I'm doing some of the above calls in my development, and the Person objects in the results don't seem to include any information about the date of birth, either in the display properties or the Facts.

Is this by design? Was hoping to avoid having to make separate ReadPerson requests for each person I find in the ancestry/descendancy in order to populate some birth events on our product's timeline.

Regards
Jamie Hirst

**Comment by stoicflame** [comment]
Can you provide some more details? Is the issue that the data isn't being returned from the API, or Is it that the C# library is failing to (de)serialize the birth?

**Comment by JamieHirstTwile** [comment]
Hi,

I'll close the issue - I discovered the FamilySearchOption setting which specifies the inclusion of the additional person details. I didn't see this in any of the SDK documentation around ancestry and descendancy, but looking into the API documentation and hunting the source code made the answer clear.

Thanks
