### ISSUE TITLE
Can't get beta data?

### ISSUE THREAD

**Issue by mseank** [FamilySearch/gedcomx-csharp#36]
I can receive data just fine on sandbox when I call with the FamilySearchFamilyTree, but when I call a person using FamilyTreePersonState on the beta server, it gives me problems, not actually retrieving any persons.

myPerson = p_Ft.ReadPersonById(item);

Parsing through the code on that line, I find two 400 errors:
"Unable to read tf person" and "Requested feature 'birth-date-not-considered-death-declaration' is not defined," though the second error may just be a fault of the first. 

I'm using ID's that I know work, as I pulled them directly from the beta site manually. I've also made sure to change the initializer of the FamilySearchFamilyTree to false, so that it knows I'm not in sandbox anymore. The dev team directed me here to ask the question.

Is this something that anyone else has encountered?

**Comment by wooddani** [comment]
As I understand, the current SDK only supports sandbox and production, hence the boolean 'useSandbox' parameter. It certainly would not difficult to add beta with the correct urls internally. We shall see shortly.

**Comment by wooddani** [comment]
Support for beta has been coded and merge request is in. You will want to confirm that your developer key has access to beta. An example of how to call beta is shown below.
`FamilySearchFamilyTree ftBeta = new FamilySearchFamilyTree(EnvironmentEnum.Beta);
var dataBeta = ftBeta.AuthenticateViaOAuth2Password(username, password, developerKey);`
