### ISSUE TITLE
Empty collection as default value for various lists

### ISSUE THREAD

**Issue by weitzhandler** [FamilySearch/gedcomx-csharp#43]
Let's start with an example, take a look at [these](https://github.com/FamilySearch/gedcomx-csharp/blob/fb8f4d7c93d29716ba88145e98783f42b9455f24/Gedcomx.Model/NamePart.cs#L30) two lines:

```
private System.Collections.Generic.List<Gx.Records.Field> _fields;
private System.Collections.Generic.List<Gx.Common.Qualifier> _qualifiers;
```

And their accessing [properties](https://github.com/FamilySearch/gedcomx-csharp/blob/fb8f4d7c93d29716ba88145e98783f42b9455f24/Gedcomx.Model/NamePart.cs#L117):

```
public System.Collections.Generic.List<Gx.Common.Qualifier> Qualifiers
{
  get
  {
    return this._qualifiers;
  }
  set
  {
    this._qualifiers = value;
  }
}
```

Now I assume the only reason these properties are not null is because they need to be serialized, but practically, they're evaluating as null many times, which makes it pretty verbose to access them having to check if they're `null`.
So my suggestion is have their getters replace with the following, to initialize them if they happen to be null:

```
get
{
  return this._qualifiers ?? (_qualifiers = new List<Qualifier>());
}
```
I haven't dug into the serializer config, but we should make sure it omits the collection if it contains no values.

I chose an example about the Qualifiers, but I'd like to see this issue addressed also in `Person.Facts` and all other collection properties.
I'd gladly do it myself if I have your green light to approve my pull.

**Comment by weitzhandler** [comment]
After digging a bit more about this, I'm still looking for a way to achieve:

1. Have all the list properties return an empty list and never null
2. Make sure this behavior doesn't impact the serializer output nor the serialization process performance (having to initialize so many lists for nothing)
3. Get rid of all those `AddFact` `SetFact` methods. `Person.Facts.Add(fact)` should be used.

**Comment by shadowca** [comment]
Hi @weitzhandler 
is this project still alive? 
First of all i would bringt the models under test. so you can directly see if your changes have impact on the serialization. Then i would change the model. 
I have forked this and try to resolve the problem of the null lists.

**Comment by weitzhandler** [comment]
Looks like the project is alive and kicking. However due to priorities I unfortunately left my genealogy project on the shelf for a while.
